# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ${{matrix.os}}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ["1.18", ">=1.18"]
        os: ["ubuntu-latest", "ubuntu-18.04"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go_version}}

      - name: Build DB
        run: docker-compose --project-directory "DevOps/CI/projeto-go-testes-main" build

      - name: Create DB
        run: docker-compose --project-directory "DevOps/CI/projeto-go-testes-main" up -d

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v DevOps/CI/projeto-go-testes-main/main.go

      - name: Upload main compilado
        uses: actions/upload-artifact@v3
        with:
          name: Aplicação-Go
          path: main

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
